FROM ubuntu:18.04

FROM python:3.10-slim-buster
RUN python -m pip install --upgrade pip
RUN pip install setuptools
RUN apt-get update && apt-get install curl -y

RUN mkdir -v /email_verifier
WORKDIR /email_verifier
COPY . .

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
ENV PATH="${PATH}:/root/.local/bin"
RUN poetry install
 
RUN mkdir /log && touch /log/error.file

RUN chmod u+x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
